### ISSUE TITLE
MTU > 1500 dosn't work

### ISSUE THREAD

**Issue by azelezniak** [att/vfd#136]
in sriov.h
line 152 should be .jumbo_frame 		= 1,

**Comment by krjoshi** [comment]
Tested with vNAT team. Seems to be working. Patch will be submitted by Alex.

**Comment by krjoshi** [comment]
DJ to add test to testing framework.

**Comment by ScottDaniels** [comment]
Two commits fix this bug:
9071539b434042e95b6139ff77239474f1f544f4
51984f6ea487160f23efec437df8c478e95a1413

Jumbo flag is set when the max mtu in the config file is >1500, and the setting in the config file is now used to configure the port rather than just to validate MTU changes requested by the guest.

both added to master on 22 March 2017.

Leaving this open until testing is completed.

**Comment by azelezniak** [comment]
tested, closed
